language: python
python:
    - "2.7"
env: CKANVERSION=2.6
before_install: cd /home/travis/build/ViderumGlobal/ckanext-opendatani
install:
    - bash bin/travis-build.bash
    - pip install coveralls -U
services:
    -postgresql: "9.1"
script: sh bin/travis-run.sh
after_success:
    - coveralls
sudo: required
cache:
  directories:
    - $HOME/.cache/pip
