language: python
python:
    - "2.6"
    - "2.7"
env:
  - CKANVERSION=2.6
  - PGVERSION=9.1
install:
    - bash bin/travis-build.bash
    - pip install coveralls
services:
    -postgresql: "9.1"
script: sh bin/travis-run.sh
after_success:
    - coveralls
