language: python
python:
    - "2.7"
env: CKANVERSION=2.6
install:
    - bash bin/travis-build.bash
    - pip install coveralls -U
addons:
    postgresql: "9.1"
env:
  global:
  - PGPORT=8983
  - PGHOST=localhost
before_script:
  - psql -c 'CREATE USER ckan_default WITH PASSWORD 'pass';' -U postgres
  - psql -c 'CREATE DATABASE ckan_test WITH OWNER ckan_default;' -U postgres
script: sh bin/travis-run.sh
after_success:
    - coveralls
sudo: required
cache:
  directories:
    - $HOME/.cache/pip
